// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ISpan.InseparableCore.Models.DAL
{
    public partial class InseparableContext : DbContext
    {
        public InseparableContext()
        {
        }

        public InseparableContext(DbContextOptions<InseparableContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TAccountStatuses> TAccountStatuses { get; set; }
        public virtual DbSet<TActivities> TActivities { get; set; }
        public virtual DbSet<TActivityParticipants> TActivityParticipants { get; set; }
        public virtual DbSet<TActors> TActors { get; set; }
        public virtual DbSet<TAdministrators> TAdministrators { get; set; }
        public virtual DbSet<TAreas> TAreas { get; set; }
        public virtual DbSet<TArticleKeywordDetails> TArticleKeywordDetails { get; set; }
        public virtual DbSet<TArticles> TArticles { get; set; }
        public virtual DbSet<TCinemas> TCinemas { get; set; }
        public virtual DbSet<TCities> TCities { get; set; }
        public virtual DbSet<TComments> TComments { get; set; }
        public virtual DbSet<TDirectors> TDirectors { get; set; }
        public virtual DbSet<TFriends> TFriends { get; set; }
        public virtual DbSet<TGenders> TGenders { get; set; }
        public virtual DbSet<TKeywords> TKeywords { get; set; }
        public virtual DbSet<TMemberFavoriteMovieCategories> TMemberFavoriteMovieCategories { get; set; }
        public virtual DbSet<TMemberPoints> TMemberPoints { get; set; }
        public virtual DbSet<TMemberReports> TMemberReports { get; set; }
        public virtual DbSet<TMembers> TMembers { get; set; }
        public virtual DbSet<TMovieActorDetails> TMovieActorDetails { get; set; }
        public virtual DbSet<TMovieCategories> TMovieCategories { get; set; }
        public virtual DbSet<TMovieCategoryDetails> TMovieCategoryDetails { get; set; }
        public virtual DbSet<TMovieDirectorDetails> TMovieDirectorDetails { get; set; }
        public virtual DbSet<TMovieKeywordDetails> TMovieKeywordDetails { get; set; }
        public virtual DbSet<TMovieLevels> TMovieLevels { get; set; }
        public virtual DbSet<TMovieScoreDetails> TMovieScoreDetails { get; set; }
        public virtual DbSet<TMovies> TMovies { get; set; }
        public virtual DbSet<TOrders> TOrders { get; set; }
        public virtual DbSet<TProductCategories> TProductCategories { get; set; }
        public virtual DbSet<TProductOrderDetails> TProductOrderDetails { get; set; }
        public virtual DbSet<TProducts> TProducts { get; set; }
        public virtual DbSet<TReports> TReports { get; set; }
        public virtual DbSet<TRooms> TRooms { get; set; }
        public virtual DbSet<TSeats> TSeats { get; set; }
        public virtual DbSet<TSessions> TSessions { get; set; }
        public virtual DbSet<TTicketOrderDetails> TTicketOrderDetails { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Chinese_Taiwan_Stroke_CI_AS");

            modelBuilder.Entity<TAccountStatuses>(entity =>
            {
                entity.HasKey(e => e.FStatusId)
                    .HasName("PK_tMemberStatus");

                entity.ToTable("tAccountStatuses");

                entity.Property(e => e.FStatusId)
                    .HasColumnName("fStatusID")
                    .HasComment("會員狀態ID");

                entity.Property(e => e.FDescription)
                    .HasMaxLength(200)
                    .HasColumnName("fDescription")
                    .HasComment("會員狀態的說明");

                entity.Property(e => e.FStatus)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fStatus")
                    .HasComment("會員狀態");
            });

            modelBuilder.Entity<TActivities>(entity =>
            {
                entity.HasKey(e => e.FId);

                entity.ToTable("tActivities");

                entity.Property(e => e.FId)
                    .HasColumnName("fID")
                    .HasComment("活動流水號");

                entity.Property(e => e.FActivityId)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fActivityID")
                    .HasComment("活動ID");

                entity.Property(e => e.FActivityTitle)
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnName("fActivityTitle")
                    .HasComment("活動標題");

                entity.Property(e => e.FCreateTime)
                    .HasColumnType("datetime")
                    .HasColumnName("fCreateTime")
                    .HasComment("活動新增時間");

                entity.Property(e => e.FDateTime)
                    .HasColumnType("datetime")
                    .HasColumnName("fDateTime")
                    .HasComment("舉辦時間");

                entity.Property(e => e.FDescription)
                    .HasMaxLength(2000)
                    .HasColumnName("fDescription")
                    .HasComment("活動描述");

                entity.Property(e => e.FmaxParticipants)
                    .HasColumnName("fmaxParticipants")
                    .HasComment("參加人數上限");
            });

            modelBuilder.Entity<TActivityParticipants>(entity =>
            {
                entity.HasKey(e => e.FId);

                entity.ToTable("tActivityParticipants");

                entity.Property(e => e.FId)
                    .HasColumnName("fID")
                    .HasComment("流水號");

                entity.Property(e => e.FActivityId)
                    .HasColumnName("fActivityID")
                    .HasComment("活動ID");

                entity.Property(e => e.FMemberId)
                    .HasColumnName("fMemberID")
                    .HasComment("參加者會員ID");

                entity.Property(e => e.FParticipantNo)
                    .HasColumnName("fParticipantNO")
                    .HasComment("報名序號");

                entity.Property(e => e.FRegisteredTime)
                    .HasColumnType("datetime")
                    .HasColumnName("fRegisteredTime")
                    .HasComment("報名時間");

                entity.HasOne(d => d.FActivity)
                    .WithMany(p => p.TActivityParticipants)
                    .HasForeignKey(d => d.FActivityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tActivityParticipants_tActivities");

                entity.HasOne(d => d.FMember)
                    .WithMany(p => p.TActivityParticipants)
                    .HasForeignKey(d => d.FMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tActivityParticipants_tMembers");
            });

            modelBuilder.Entity<TActors>(entity =>
            {
                entity.HasKey(e => e.FActorId);

                entity.ToTable("tActors");

                entity.Property(e => e.FActorId).HasColumnName("fActorID");

                entity.Property(e => e.FActorName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fActorName");
            });

            modelBuilder.Entity<TAdministrators>(entity =>
            {
                entity.HasKey(e => e.FId);

                entity.ToTable("tAdministrators");

                entity.Property(e => e.FId)
                    .HasColumnName("fID")
                    .HasComment("管理員流水號");

                entity.Property(e => e.FAdministratorId)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fAdministratorID")
                    .HasComment("管理員ID");

                entity.Property(e => e.FEmail)
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnName("fEmail")
                    .HasComment("管理員電子郵件地址");

                entity.Property(e => e.FFirstName)
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnName("fFirstName")
                    .HasComment("管理員名字");

                entity.Property(e => e.FLastName)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("fLastName")
                    .HasComment("管理員姓氏");

                entity.Property(e => e.FPasswordHash)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("fPasswordHash")
                    .HasComment("管理員密碼加密值");

                entity.Property(e => e.FPasswordSalt)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fPasswordSalt")
                    .HasComment("管理員密碼鹽值");

                entity.Property(e => e.FSignUpTime)
                    .HasColumnType("datetime")
                    .HasColumnName("fSignUpTime")
                    .HasComment("管理員註冊時間");
            });

            modelBuilder.Entity<TAreas>(entity =>
            {
                entity.HasKey(e => e.FId);

                entity.ToTable("tAreas");

                entity.Property(e => e.FId)
                    .HasColumnName("fID")
                    .HasComment("鄉鎮市區的流水號");

                entity.Property(e => e.FAreaName)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("fAreaName")
                    .HasComment("鄉鎮市區的名稱");

                entity.Property(e => e.FCityId)
                    .HasColumnName("fCityID")
                    .HasComment("鄉鎮市區所屬縣市");

                entity.Property(e => e.FZipCode)
                    .HasColumnName("fZipCode")
                    .HasComment("鄉鎮市區的郵遞區號");

                entity.HasOne(d => d.FCity)
                    .WithMany(p => p.TAreas)
                    .HasForeignKey(d => d.FCityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Areas_Cities");
            });

            modelBuilder.Entity<TArticleKeywordDetails>(entity =>
            {
                entity.HasKey(e => e.FSerialNumber)
                    .HasName("PK_ArticleCategoryDetails");

                entity.ToTable("tArticleKeywordDetails");

                entity.HasIndex(e => new { e.FArticleId, e.FKeywordId }, "IX_tArticleKeywordDetails")
                    .IsUnique();

                entity.Property(e => e.FSerialNumber).HasColumnName("fSerialNumber");

                entity.Property(e => e.FArticleId).HasColumnName("fArticleID");

                entity.Property(e => e.FKeywordId).HasColumnName("fKeywordID");

                entity.HasOne(d => d.FArticle)
                    .WithMany(p => p.TArticleKeywordDetails)
                    .HasForeignKey(d => d.FArticleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tKeywordDetails_Articles");

                entity.HasOne(d => d.FKeyword)
                    .WithMany(p => p.TArticleKeywordDetails)
                    .HasForeignKey(d => d.FKeywordId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ArticleCategoryDetails_ArticleCategories");
            });

            modelBuilder.Entity<TArticles>(entity =>
            {
                entity.HasKey(e => e.FArticleId)
                    .HasName("PK_Article");

                entity.ToTable("tArticles");

                entity.Property(e => e.FArticleId).HasColumnName("fArticleID");

                entity.Property(e => e.FArticleCategoryId).HasColumnName("fArticleCategoryID");

                entity.Property(e => e.FArticleClicks).HasColumnName("fArticleClicks");

                entity.Property(e => e.FArticleContent)
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnName("fArticleContent");

                entity.Property(e => e.FArticleLikes).HasColumnName("fArticleLikes");

                entity.Property(e => e.FArticlePostingDate)
                    .HasColumnType("datetime")
                    .HasColumnName("fArticlePostingDate")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.FArticleTitle)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fArticleTitle");

                entity.Property(e => e.FDeleted).HasColumnName("fDeleted");

                entity.Property(e => e.FMemberId).HasColumnName("fMemberID");

                entity.HasOne(d => d.FArticleCategory)
                    .WithMany(p => p.TArticles)
                    .HasForeignKey(d => d.FArticleCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tArticles_tMovieCategories");

                entity.HasOne(d => d.FMember)
                    .WithMany(p => p.TArticles)
                    .HasForeignKey(d => d.FMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tArticles_tMembers");
            });

            modelBuilder.Entity<TCinemas>(entity =>
            {
                entity.HasKey(e => e.FCinemaId)
                    .HasName("PK_MovieManages");

                entity.ToTable("tCinemas");

                entity.HasIndex(e => e.FCinemaName, "IX_Cinemas")
                    .IsUnique();

                entity.Property(e => e.FCinemaId).HasColumnName("fCinemaID");

                entity.Property(e => e.FCinemaAddress)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("fCinemaAddress");

                entity.Property(e => e.FCinemaName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fCinemaName");

                entity.Property(e => e.FCinemaRegion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fCinemaRegion");

                entity.Property(e => e.FCinemaTel)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fCinemaTel");

                entity.Property(e => e.FLat).HasColumnName("fLat");

                entity.Property(e => e.FLng).HasColumnName("fLng");

                entity.Property(e => e.FTraffic)
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnName("fTraffic");
            });

            modelBuilder.Entity<TCities>(entity =>
            {
                entity.HasKey(e => e.FCityId)
                    .HasName("PK_Cities");

                entity.ToTable("tCities");

                entity.Property(e => e.FCityId)
                    .ValueGeneratedNever()
                    .HasColumnName("fCityID");

                entity.Property(e => e.FCityName)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("fCityName");
            });

            modelBuilder.Entity<TComments>(entity =>
            {
                entity.HasKey(e => e.FCommentId);

                entity.ToTable("tComments");

                entity.Property(e => e.FCommentId).HasColumnName("fCommentID");

                entity.Property(e => e.FArticleId).HasColumnName("fArticleID");

                entity.Property(e => e.FCommentContent)
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnName("fCommentContent");

                entity.Property(e => e.FCommentLikes).HasColumnName("fCommentLikes");

                entity.Property(e => e.FCommentPostingDate)
                    .HasColumnType("datetime")
                    .HasColumnName("fCommentPostingDate")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.FDeleted).HasColumnName("fDeleted");

                entity.Property(e => e.FItemNumber).HasColumnName("fItemNumber");

                entity.Property(e => e.FMemberId).HasColumnName("fMemberID");

                entity.HasOne(d => d.FArticle)
                    .WithMany(p => p.TComments)
                    .HasForeignKey(d => d.FArticleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Comments_Article");

                entity.HasOne(d => d.FMember)
                    .WithMany(p => p.TComments)
                    .HasForeignKey(d => d.FMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tComments_tMembers");
            });

            modelBuilder.Entity<TDirectors>(entity =>
            {
                entity.HasKey(e => e.FDirectorId);

                entity.ToTable("tDirectors");

                entity.Property(e => e.FDirectorId).HasColumnName("fDirectorID");

                entity.Property(e => e.FDitectorName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fDitectorName");
            });

            modelBuilder.Entity<TFriends>(entity =>
            {
                entity.HasKey(e => e.FId);

                entity.ToTable("tFriends");

                entity.Property(e => e.FId)
                    .HasColumnName("fID")
                    .HasComment("好友流水號");

                entity.Property(e => e.FFriendDateTime)
                    .HasColumnType("datetime")
                    .HasColumnName("fFriendDateTime")
                    .HasComment("成為好友的時間");

                entity.Property(e => e.FFriendId)
                    .HasColumnName("fFriendID")
                    .HasComment("好友的ID");

                entity.Property(e => e.FFriendNo)
                    .HasColumnName("fFriendNo")
                    .HasComment("好友的序號");

                entity.Property(e => e.FMemberId)
                    .HasColumnName("fMemberID")
                    .HasComment("會員ID");

                entity.HasOne(d => d.FMember)
                    .WithMany(p => p.TFriends)
                    .HasForeignKey(d => d.FMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tFriends_tMembers");
            });

            modelBuilder.Entity<TGenders>(entity =>
            {
                entity.HasKey(e => e.FGenderId)
                    .HasName("PK_Gender");

                entity.ToTable("tGenders");

                entity.Property(e => e.FGenderId)
                    .HasColumnName("fGenderID")
                    .HasComment("性別ID");

                entity.Property(e => e.FGenderType)
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnName("fGenderType")
                    .HasComment("性別種類");
            });

            modelBuilder.Entity<TKeywords>(entity =>
            {
                entity.HasKey(e => e.FKeywordId)
                    .HasName("PK_ArticleCategories");

                entity.ToTable("tKeywords");

                entity.Property(e => e.FKeywordId).HasColumnName("fKeywordID");

                entity.Property(e => e.FKeywordName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fKeywordName");
            });

            modelBuilder.Entity<TMemberFavoriteMovieCategories>(entity =>
            {
                entity.HasKey(e => e.FId)
                    .HasName("PK_MemberFavoriteMovieCategories");

                entity.ToTable("tMemberFavoriteMovieCategories");

                entity.Property(e => e.FId).HasColumnName("fID");

                entity.Property(e => e.FMemberId).HasColumnName("fMemberID");

                entity.Property(e => e.FMovieCategoryId).HasColumnName("fMovieCategoryID");

                entity.HasOne(d => d.FMember)
                    .WithMany(p => p.TMemberFavoriteMovieCategories)
                    .HasForeignKey(d => d.FMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMemberFavoriteMovieCategories_tMembers");

                entity.HasOne(d => d.FMovieCategory)
                    .WithMany(p => p.TMemberFavoriteMovieCategories)
                    .HasForeignKey(d => d.FMovieCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_MemberFavoriteMovieCategories_MovieCategories");
            });

            modelBuilder.Entity<TMemberPoints>(entity =>
            {
                entity.HasKey(e => e.FMemberPointId)
                    .HasName("PK_MemberPoints");

                entity.ToTable("tMemberPoints");

                entity.Property(e => e.FMemberPointId)
                    .HasColumnName("fMemberPointID")
                    .HasComment("會員點數的流水號");

                entity.Property(e => e.FCreateTime)
                    .HasColumnType("datetime")
                    .HasColumnName("fCreateTime")
                    .HasComment("點數異動的時間");

                entity.Property(e => e.FDescription)
                    .HasMaxLength(100)
                    .HasColumnName("fDescription")
                    .HasComment("點數異動原因");

                entity.Property(e => e.FItemNo).HasColumnName("fItemNO");

                entity.Property(e => e.FMemberId)
                    .HasColumnName("fMemberID")
                    .HasComment("會員ID");

                entity.Property(e => e.FPointDeducted)
                    .HasColumnName("fPointDeducted")
                    .HasComment("扣點數量");

                entity.Property(e => e.FPointsAdded)
                    .HasColumnName("fPointsAdded")
                    .HasComment("新增點數數量");

                entity.HasOne(d => d.FMember)
                    .WithMany(p => p.TMemberPoints)
                    .HasForeignKey(d => d.FMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMemberPoints_tMembers");
            });

            modelBuilder.Entity<TMemberReports>(entity =>
            {
                entity.HasKey(e => e.FMemberReportId)
                    .HasName("PK_tReport");

                entity.ToTable("tMemberReports");

                entity.Property(e => e.FMemberReportId)
                    .ValueGeneratedNever()
                    .HasColumnName("fMemberReportID")
                    .HasComment("檢舉的流水號");

                entity.Property(e => e.FReportMemberId)
                    .HasColumnName("fReportMemberID")
                    .HasComment("檢舉者的會員ID");

                entity.Property(e => e.FReportTime)
                    .HasColumnType("datetime")
                    .HasColumnName("fReportTime")
                    .HasDefaultValueSql("(getdate())")
                    .HasComment("檢舉時間");

                entity.Property(e => e.FReportType)
                    .HasColumnName("fReportType")
                    .HasComment("檢舉類型");

                entity.Property(e => e.FReportedMemberId)
                    .HasColumnName("fReportedMemberID")
                    .HasComment("被檢舉的會員ID");

                entity.HasOne(d => d.FReportMember)
                    .WithMany(p => p.TMemberReportsFReportMember)
                    .HasForeignKey(d => d.FReportMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMemberReports_tMembers1");

                entity.HasOne(d => d.FReportTypeNavigation)
                    .WithMany(p => p.TMemberReports)
                    .HasForeignKey(d => d.FReportType)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMemberReports_tReports");

                entity.HasOne(d => d.FReportedMember)
                    .WithMany(p => p.TMemberReportsFReportedMember)
                    .HasForeignKey(d => d.FReportedMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMemberReports_tMembers");
            });

            modelBuilder.Entity<TMembers>(entity =>
            {
                entity.HasKey(e => e.FId)
                    .HasName("PK_Members");

                entity.ToTable("tMembers");

                entity.Property(e => e.FId)
                    .HasColumnName("fID")
                    .HasComment("會員流水號");

                entity.Property(e => e.FAccountStatus)
                    .HasColumnName("fAccountStatus")
                    .HasComment("會員帳戶狀態");

                entity.Property(e => e.FAddress)
                    .HasMaxLength(100)
                    .HasColumnName("fAddress")
                    .HasComment("住址");

                entity.Property(e => e.FAreaId)
                    .HasColumnName("fAreaID")
                    .HasComment("區域ID");

                entity.Property(e => e.FCellphone)
                    .HasMaxLength(50)
                    .HasColumnName("fCellphone")
                    .HasComment("手機號碼");

                entity.Property(e => e.FDateOfBirth)
                    .HasColumnType("date")
                    .HasColumnName("fDateOfBirth")
                    .HasComment("生日");

                entity.Property(e => e.FEmail)
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnName("fEmail")
                    .HasComment("電子郵件的地址");

                entity.Property(e => e.FFirstName)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("fFirstName")
                    .HasComment("名字");

                entity.Property(e => e.FGenderId)
                    .HasColumnName("fGenderID")
                    .HasComment("性別ID");

                entity.Property(e => e.FIntroduction)
                    .HasMaxLength(500)
                    .HasColumnName("fIntroduction")
                    .HasComment("個人簡介");

                entity.Property(e => e.FLastName)
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnName("fLastName")
                    .HasComment("姓氏");

                entity.Property(e => e.FMemberId)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fMemberID")
                    .HasComment("會員ID");

                entity.Property(e => e.FPasswordHash)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("fPasswordHash")
                    .HasComment("密碼加密值");

                entity.Property(e => e.FPasswordSalt)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fPasswordSalt")
                    .HasComment("密碼鹽值");

                entity.Property(e => e.FPhotoPath)
                    .HasMaxLength(200)
                    .HasColumnName("fPhotoPath")
                    .HasComment("大頭貼的檔案路徑");

                entity.Property(e => e.FSignUpTime)
                    .HasColumnType("datetime")
                    .HasColumnName("fSignUpTime")
                    .HasComment("會員註冊時間");

                entity.Property(e => e.FTotalMemberPoint)
                    .HasColumnName("fTotalMemberPoint")
                    .HasComment("目前點數餘額");

                entity.HasOne(d => d.FAccountStatusNavigation)
                    .WithMany(p => p.TMembers)
                    .HasForeignKey(d => d.FAccountStatus)
                    .HasConstraintName("FK_tMembers_tAccountStatuses");

                entity.HasOne(d => d.FArea)
                    .WithMany(p => p.TMembers)
                    .HasForeignKey(d => d.FAreaId)
                    .HasConstraintName("FK_tMembers_tAreas");

                entity.HasOne(d => d.FGender)
                    .WithMany(p => p.TMembers)
                    .HasForeignKey(d => d.FGenderId)
                    .HasConstraintName("FK_tMembers_tGenders");
            });

            modelBuilder.Entity<TMovieActorDetails>(entity =>
            {
                entity.HasKey(e => e.FSerialNumber)
                    .HasName("PK_MovieActorDetails");

                entity.ToTable("tMovieActorDetails");

                entity.HasIndex(e => new { e.FMovieId, e.FActorId }, "IX_tMovieActorDetails")
                    .IsUnique();

                entity.Property(e => e.FSerialNumber).HasColumnName("fSerialNumber");

                entity.Property(e => e.FActorId).HasColumnName("fActorID");

                entity.Property(e => e.FMovieId).HasColumnName("fMovieID");

                entity.HasOne(d => d.FActor)
                    .WithMany(p => p.TMovieActorDetails)
                    .HasForeignKey(d => d.FActorId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_MovieActorDetails_tActors");

                entity.HasOne(d => d.FMovie)
                    .WithMany(p => p.TMovieActorDetails)
                    .HasForeignKey(d => d.FMovieId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_MovieActorDetails_tMovies");
            });

            modelBuilder.Entity<TMovieCategories>(entity =>
            {
                entity.HasKey(e => e.FMovieCategoryId)
                    .HasName("PK_MovieCategories");

                entity.ToTable("tMovieCategories");

                entity.Property(e => e.FMovieCategoryId).HasColumnName("fMovieCategoryID");

                entity.Property(e => e.FMovieCategoryName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fMovieCategoryName");
            });

            modelBuilder.Entity<TMovieCategoryDetails>(entity =>
            {
                entity.HasKey(e => e.FSerialNumber)
                    .HasName("PK_MovieCategoryDetails_1");

                entity.ToTable("tMovieCategoryDetails");

                entity.HasIndex(e => new { e.FMovieCategoryId, e.FMovieId }, "IX_tMovieCategoryDetails")
                    .IsUnique();

                entity.Property(e => e.FSerialNumber).HasColumnName("fSerialNumber");

                entity.Property(e => e.FMovieCategoryId).HasColumnName("fMovieCategoryID");

                entity.Property(e => e.FMovieId).HasColumnName("fMovieID");

                entity.HasOne(d => d.FMovieCategory)
                    .WithMany(p => p.TMovieCategoryDetails)
                    .HasForeignKey(d => d.FMovieCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_MovieCategoryDetails_MovieCategories");

                entity.HasOne(d => d.FMovie)
                    .WithMany(p => p.TMovieCategoryDetails)
                    .HasForeignKey(d => d.FMovieId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_MovieCategoryDetails_Movies");
            });

            modelBuilder.Entity<TMovieDirectorDetails>(entity =>
            {
                entity.HasKey(e => e.FSerialNumber);

                entity.ToTable("tMovieDirectorDetails");

                entity.HasIndex(e => new { e.FDirectorId, e.FMovieId }, "IX_tMovieDirectorDetails")
                    .IsUnique();

                entity.Property(e => e.FSerialNumber).HasColumnName("fSerialNumber");

                entity.Property(e => e.FDirectorId).HasColumnName("fDirectorID");

                entity.Property(e => e.FMovieId).HasColumnName("fMovieID");

                entity.HasOne(d => d.FDirector)
                    .WithMany(p => p.TMovieDirectorDetails)
                    .HasForeignKey(d => d.FDirectorId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMovieDirectorDetails_tDirectors");

                entity.HasOne(d => d.FMovie)
                    .WithMany(p => p.TMovieDirectorDetails)
                    .HasForeignKey(d => d.FMovieId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMovieDirectorDetails_tMovies");
            });

            modelBuilder.Entity<TMovieKeywordDetails>(entity =>
            {
                entity.HasKey(e => e.FSerialNumber);

                entity.ToTable("tMovieKeywordDetails");

                entity.HasIndex(e => new { e.FKeywordId, e.FMovieId }, "IX_tMovieKeywordDetails")
                    .IsUnique();

                entity.Property(e => e.FSerialNumber).HasColumnName("fSerialNumber");

                entity.Property(e => e.FKeywordId).HasColumnName("fKeywordID");

                entity.Property(e => e.FMovieId).HasColumnName("fMovieID");

                entity.HasOne(d => d.FKeyword)
                    .WithMany(p => p.TMovieKeywordDetails)
                    .HasForeignKey(d => d.FKeywordId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMovieKeywordDetails_tKeywords");

                entity.HasOne(d => d.FMovie)
                    .WithMany(p => p.TMovieKeywordDetails)
                    .HasForeignKey(d => d.FMovieId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMovieKeywordDetails_tMovies");
            });

            modelBuilder.Entity<TMovieLevels>(entity =>
            {
                entity.HasKey(e => e.FLevelId)
                    .HasName("PK_MovieLevels");

                entity.ToTable("tMovieLevels");

                entity.Property(e => e.FLevelId).HasColumnName("fLevelID");

                entity.Property(e => e.FLevelName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fLevelName");
            });

            modelBuilder.Entity<TMovieScoreDetails>(entity =>
            {
                entity.HasKey(e => e.FSerialNumber);

                entity.ToTable("tMovieScoreDetails");

                entity.HasIndex(e => new { e.FMemberId, e.FMovieId }, "IX_tMovieScoreDetails")
                    .IsUnique();

                entity.Property(e => e.FSerialNumber)
                    .ValueGeneratedNever()
                    .HasColumnName("fSerialNumber");

                entity.Property(e => e.FMemberId).HasColumnName("fMemberId");

                entity.Property(e => e.FMovieId).HasColumnName("fMovieId");

                entity.Property(e => e.FScore).HasColumnName("fScore");

                entity.HasOne(d => d.FMember)
                    .WithMany(p => p.TMovieScoreDetails)
                    .HasForeignKey(d => d.FMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMovieScoreDetails_tMembers");

                entity.HasOne(d => d.FMovie)
                    .WithMany(p => p.TMovieScoreDetails)
                    .HasForeignKey(d => d.FMovieId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tMovieScoreDetails_tMovies");
            });

            modelBuilder.Entity<TMovies>(entity =>
            {
                entity.HasKey(e => e.FMovieId)
                    .HasName("PK_Movies");

                entity.ToTable("tMovies");

                entity.Property(e => e.FMovieId).HasColumnName("fMovieID");

                entity.Property(e => e.FMovieImagePath)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fMovieImagePath")
                    .HasDefaultValueSql("('no image')");

                entity.Property(e => e.FMovieIntroduction)
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnName("fMovieIntroduction");

                entity.Property(e => e.FMovieLength).HasColumnName("fMovieLength");

                entity.Property(e => e.FMovieLevelId).HasColumnName("fMovieLevelID");

                entity.Property(e => e.FMovieName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fMovieName");

                entity.Property(e => e.FMovieOffDate)
                    .HasColumnType("date")
                    .HasColumnName("fMovieOffDate");

                entity.Property(e => e.FMovieOnDate)
                    .HasColumnType("date")
                    .HasColumnName("fMovieOnDate");

                entity.Property(e => e.FMovieScore).HasColumnName("fMovieScore");

                entity.HasOne(d => d.FMovieLevel)
                    .WithMany(p => p.TMovies)
                    .HasForeignKey(d => d.FMovieLevelId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Movies_MovieLevels");
            });

            modelBuilder.Entity<TOrders>(entity =>
            {
                entity.HasKey(e => e.FOrderId)
                    .HasName("PK_Order");

                entity.ToTable("tOrders");

                entity.Property(e => e.FOrderId).HasColumnName("fOrderID");

                entity.Property(e => e.FCinemaId).HasColumnName("fCinemaID");

                entity.Property(e => e.FMemberId).HasColumnName("fMemberID");

                entity.Property(e => e.FModifiedTime)
                    .HasColumnType("datetime")
                    .HasColumnName("fModifiedTime");

                entity.Property(e => e.FOrderDate)
                    .HasColumnType("datetime")
                    .HasColumnName("fOrderDate");

                entity.Property(e => e.FStatus).HasColumnName("fStatus");

                entity.Property(e => e.FTotalMoney)
                    .HasColumnType("money")
                    .HasColumnName("fTotalMoney");

                entity.HasOne(d => d.FCinema)
                    .WithMany(p => p.TOrders)
                    .HasForeignKey(d => d.FCinemaId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Orders_Cinemas");

                entity.HasOne(d => d.FMember)
                    .WithMany(p => p.TOrders)
                    .HasForeignKey(d => d.FMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tOrders_tMembers");
            });

            modelBuilder.Entity<TProductCategories>(entity =>
            {
                entity.HasKey(e => e.FProductCategoryId)
                    .HasName("PK_ProductCategories");

                entity.ToTable("tProductCategories");

                entity.Property(e => e.FProductCategoryId).HasColumnName("fProductCategoryID");

                entity.Property(e => e.FProductCategoryName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fProductCategoryName");
            });

            modelBuilder.Entity<TProductOrderDetails>(entity =>
            {
                entity.HasKey(e => e.FId)
                    .HasName("PK_ProductOrderDetials");

                entity.ToTable("tProductOrderDetails");

                entity.Property(e => e.FId).HasColumnName("fID");

                entity.Property(e => e.FOrderId).HasColumnName("fOrderID");

                entity.Property(e => e.FProductDiscount)
                    .HasColumnType("decimal(18, 2)")
                    .HasColumnName("fProductDiscount");

                entity.Property(e => e.FProductId).HasColumnName("fProductID");

                entity.Property(e => e.FProductItemNo).HasColumnName("fProductItem_no");

                entity.Property(e => e.FProductName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fProductName");

                entity.Property(e => e.FProductQty).HasColumnName("fProductQty");

                entity.Property(e => e.FProductSubtotal)
                    .HasColumnType("money")
                    .HasColumnName("fProductSubtotal");

                entity.Property(e => e.FProductUnitprice)
                    .HasColumnType("money")
                    .HasColumnName("fProductUnitprice");

                entity.HasOne(d => d.FOrder)
                    .WithMany(p => p.TProductOrderDetails)
                    .HasForeignKey(d => d.FOrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ProductOrderDetails_Orders");

                entity.HasOne(d => d.FProduct)
                    .WithMany(p => p.TProductOrderDetails)
                    .HasForeignKey(d => d.FProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ProductOrderDetails_Products");
            });

            modelBuilder.Entity<TProducts>(entity =>
            {
                entity.HasKey(e => e.FProductId)
                    .HasName("PK_Products");

                entity.ToTable("tProducts");

                entity.Property(e => e.FProductId).HasColumnName("fProductId");

                entity.Property(e => e.FCinemaId).HasColumnName("fCinemaID");

                entity.Property(e => e.FProductCategoryId).HasColumnName("fProductCategoryId");

                entity.Property(e => e.FProductName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fProductName");

                entity.Property(e => e.FProductPicturePath)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fProductPicturePath");

                entity.Property(e => e.FProductStock).HasColumnName("fProductStock");

                entity.Property(e => e.FProductUnitprice)
                    .HasColumnType("money")
                    .HasColumnName("fProductUnitprice");

                entity.HasOne(d => d.FCinema)
                    .WithMany(p => p.TProducts)
                    .HasForeignKey(d => d.FCinemaId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Products_Cinemas");

                entity.HasOne(d => d.FProductCategory)
                    .WithMany(p => p.TProducts)
                    .HasForeignKey(d => d.FProductCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Products_ProductCategories");
            });

            modelBuilder.Entity<TReports>(entity =>
            {
                entity.HasKey(e => e.FReportTypeId);

                entity.ToTable("tReports");

                entity.Property(e => e.FReportTypeId)
                    .HasColumnName("fReportTypeID")
                    .HasComment("檢舉類型ID");

                entity.Property(e => e.FDescription)
                    .HasMaxLength(200)
                    .HasColumnName("fDescription")
                    .HasComment("檢舉類型的詳細描述");

                entity.Property(e => e.FReportType)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fReportType")
                    .HasComment("檢舉類型");
            });

            modelBuilder.Entity<TRooms>(entity =>
            {
                entity.HasKey(e => e.FRoomId)
                    .HasName("PK_Rooms");

                entity.ToTable("tRooms");

                entity.Property(e => e.FRoomId).HasColumnName("fRoomID");

                entity.Property(e => e.FCinemaId).HasColumnName("fCinemaID");

                entity.Property(e => e.FRoomName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fRoomName");

                entity.HasOne(d => d.FCinema)
                    .WithMany(p => p.TRooms)
                    .HasForeignKey(d => d.FCinemaId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Rooms_Cinemas");
            });

            modelBuilder.Entity<TSeats>(entity =>
            {
                entity.HasKey(e => e.FSeatId)
                    .HasName("PK_Seats");

                entity.ToTable("tSeats");

                entity.Property(e => e.FSeatId).HasColumnName("fSeatID");

                entity.Property(e => e.FSeatColumn).HasColumnName("fSeatColumn");

                entity.Property(e => e.FSeatRow)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fSeatRow");
            });

            modelBuilder.Entity<TSessions>(entity =>
            {
                entity.HasKey(e => e.FSessionId)
                    .HasName("PK_Session");

                entity.ToTable("tSessions");

                entity.Property(e => e.FSessionId).HasColumnName("fSessionId");

                entity.Property(e => e.FCinemaId).HasColumnName("fCinemaID");

                entity.Property(e => e.FMovieId).HasColumnName("fMovieId");

                entity.Property(e => e.FRoomId).HasColumnName("fRoomId");

                entity.Property(e => e.FSessionDate)
                    .HasColumnType("date")
                    .HasColumnName("fSessionDate");

                entity.Property(e => e.FSessionTime).HasColumnName("fSessionTime");

                entity.Property(e => e.FTicketPrice)
                    .HasColumnType("money")
                    .HasColumnName("fTicketPrice");

                entity.HasOne(d => d.FCinema)
                    .WithMany(p => p.TSessions)
                    .HasForeignKey(d => d.FCinemaId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Sessions_Cinemas");

                entity.HasOne(d => d.FMovie)
                    .WithMany(p => p.TSessions)
                    .HasForeignKey(d => d.FMovieId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Sessions_Movies");

                entity.HasOne(d => d.FRoom)
                    .WithMany(p => p.TSessions)
                    .HasForeignKey(d => d.FRoomId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Sessions_Rooms");
            });

            modelBuilder.Entity<TTicketOrderDetails>(entity =>
            {
                entity.HasKey(e => e.FId)
                    .HasName("PK_TicketOrderDetial");

                entity.ToTable("tTicketOrderDetails");

                entity.Property(e => e.FId).HasColumnName("fID");

                entity.Property(e => e.FMovieId).HasColumnName("fMovieID");

                entity.Property(e => e.FMovieName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("fMovieName");

                entity.Property(e => e.FOrderId).HasColumnName("fOrderID");

                entity.Property(e => e.FRoomId).HasColumnName("fRoomID");

                entity.Property(e => e.FSeatId).HasColumnName("fSeatID");

                entity.Property(e => e.FSessionId).HasColumnName("fSessionID");

                entity.Property(e => e.FStatus).HasColumnName("fStatus");

                entity.Property(e => e.FTicketDiscount)
                    .HasColumnType("decimal(18, 2)")
                    .HasColumnName("fTicketDiscount");

                entity.Property(e => e.FTicketItemNo).HasColumnName("fTicketItem_no");

                entity.Property(e => e.FTicketSubtotal)
                    .HasColumnType("money")
                    .HasColumnName("fTicketSubtotal");

                entity.Property(e => e.FTicketUnitprice)
                    .HasColumnType("money")
                    .HasColumnName("fTicketUnitprice");

                entity.HasOne(d => d.FMovie)
                    .WithMany(p => p.TTicketOrderDetails)
                    .HasForeignKey(d => d.FMovieId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TicketOrderDetails_Movies");

                entity.HasOne(d => d.FOrder)
                    .WithMany(p => p.TTicketOrderDetails)
                    .HasForeignKey(d => d.FOrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TicketOrderDetails_Orders");

                entity.HasOne(d => d.FRoom)
                    .WithMany(p => p.TTicketOrderDetails)
                    .HasForeignKey(d => d.FRoomId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TicketOrderDetails_Rooms");

                entity.HasOne(d => d.FSeat)
                    .WithMany(p => p.TTicketOrderDetails)
                    .HasForeignKey(d => d.FSeatId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TicketOrderDetails_Seats");

                entity.HasOne(d => d.FSession)
                    .WithMany(p => p.TTicketOrderDetails)
                    .HasForeignKey(d => d.FSessionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TicketOrderDetails_Sessions");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}