// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models.DAL
{
    public partial class TAreas
    {
        public TAreas()
        {
            TMembers = new HashSet<TMembers>();
        }

        /// <summary>
        /// 鄉鎮市區的郵遞區號
        /// </summary>
        public int FZipCode { get; set; }
        /// <summary>
        /// 鄉鎮市區所屬縣市
        /// </summary>
        public int FCityId { get; set; }
        /// <summary>
        /// 鄉鎮市區的名稱
        /// </summary>
        public string FAreaName { get; set; }

        public virtual TCities FCity { get; set; }
        public virtual ICollection<TMembers> TMembers { get; set; }
    }
}