// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models.DAL
{
    public partial class TArticleClickedDetails
    {
        public int FSerialNumber { get; set; }
        public int FMemberId { get; set; }
        public int FArticleId { get; set; }
        public bool FLikeClicked { get; set; }

        public virtual TArticles FArticle { get; set; }
        public virtual TMembers FMember { get; set; }
    }
}