// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models.DAL
{
    public partial class TArticles
    {
        public TArticles()
        {
            TArticleClickedDetails = new HashSet<TArticleClickedDetails>();
            TArticleKeywordDetails = new HashSet<TArticleKeywordDetails>();
            TArticleLikeDetails = new HashSet<TArticleLikeDetails>();
            TComments = new HashSet<TComments>();
        }

        public int FArticleId { get; set; }
        public string FArticleTitle { get; set; }
        public int FMemberId { get; set; }
        public int FArticleCategoryId { get; set; }
        public DateTime FArticlePostingDate { get; set; }
        public DateTime FArticleModifiedDate { get; set; }
        public int FArticleLikes { get; set; }
        public int FArticleClicks { get; set; }
        public string FArticleContent { get; set; }
        public bool FDeleted { get; set; }

        public virtual TMovieCategories FArticleCategory { get; set; }
        public virtual TMembers FMember { get; set; }
        public virtual ICollection<TArticleClickedDetails> TArticleClickedDetails { get; set; }
        public virtual ICollection<TArticleKeywordDetails> TArticleKeywordDetails { get; set; }
        public virtual ICollection<TArticleLikeDetails> TArticleLikeDetails { get; set; }
        public virtual ICollection<TComments> TComments { get; set; }
    }
}