// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models.DAL
{
    public partial class TChat
    {
        public int FId { get; set; }
        /// <summary>
        /// 發送者的會員ID
        /// </summary>
        public int? FSenderId { get; set; }
        public int? FReceiverId { get; set; }
        public string FMessage { get; set; }
        public DateTime FTime { get; set; }
    }
}