// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models.DAL
{
    public partial class TGenders
    {
        public TGenders()
        {
            TMembers = new HashSet<TMembers>();
        }

        /// <summary>
        /// 性別ID
        /// </summary>
        public int FGenderId { get; set; }
        /// <summary>
        /// 性別種類
        /// </summary>
        public string FGenderType { get; set; }

        public virtual ICollection<TMembers> TMembers { get; set; }
    }
}