// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models.DAL
{
    public partial class TMovieCategoryDetails
    {
        public int FSerialNumber { get; set; }
        public int FMovieId { get; set; }
        public int FMovieCategoryId { get; set; }

        public virtual TMovies FMovie { get; set; }
        public virtual TMovieCategories FMovieCategory { get; set; }
    }
}