// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models.DAL
{
    public partial class TMovieScoreDetails
    {
        public int FSerialNumber { get; set; }
        public int FMovieId { get; set; }
        public int FMemberId { get; set; }
        public int FScore { get; set; }

        public virtual TMembers FMember { get; set; }
        public virtual TMovies FMovie { get; set; }
    }
}