// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models.DAL
{
    public partial class TMovieActorDetails
    {
        public int FSerialNumber { get; set; }
        public int FActorId { get; set; }
        public int FMovieId { get; set; }

        public virtual TActors FActor { get; set; }
        public virtual TMovies FMovie { get; set; }
    }
}