// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models.DAL
{
    public partial class TProducts
    {
        public TProducts()
        {
            TProductOrderDetails = new HashSet<TProductOrderDetails>();
        }

        public int FProductId { get; set; }
        public string FProductName { get; set; }
        public int FProductCategoryId { get; set; }
        public decimal FProductUnitprice { get; set; }
        public int FProductStock { get; set; }
        public string FProductPicturePath { get; set; }
        public int FCinemaId { get; set; }

        public virtual TCinemas FCinema { get; set; }
        public virtual TProductCategories FProductCategory { get; set; }
        public virtual ICollection<TProductOrderDetails> TProductOrderDetails { get; set; }
    }
}