// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TAccountStatus
    {
        /// <summary>
        /// 會員狀態ID
        /// </summary>
        public int FStatusId { get; set; }
        /// <summary>
        /// 會員狀態
        /// </summary>
        public string FStatus { get; set; }
        /// <summary>
        /// 會員狀態的說明
        /// </summary>
        public string FDescription { get; set; }
    }
}