// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TActors
    {
        public TActors()
        {
            TMovieActorDetails = new HashSet<TMovieActorDetails>();
        }

        public int FActorId { get; set; }
        public string FActorName { get; set; }

        public virtual ICollection<TMovieActorDetails> TMovieActorDetails { get; set; }
    }
}