// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TActivityParticipants
    {
        public int FId { get; set; }
        public int FActivityId { get; set; }
        public int? FParticipantNo { get; set; }
        public int FMemberId { get; set; }
        public string FRegisteredTime { get; set; }

        public virtual TActivities FActivity { get; set; }
        public virtual TMembers FMember { get; set; }
    }
}