// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TActivities
    {
        public TActivities()
        {
            TActivityParticipants = new HashSet<TActivityParticipants>();
        }

        /// <summary>
        /// 活動流水號
        /// </summary>
        public int FId { get; set; }
        /// <summary>
        /// 活動ID
        /// </summary>
        public string FActivityId { get; set; }
        /// <summary>
        /// 活動標題
        /// </summary>
        public string FActivityTitle { get; set; }
        /// <summary>
        /// 舉辦時間
        /// </summary>
        public DateTime FDateTime { get; set; }
        /// <summary>
        /// 參加人數上限
        /// </summary>
        public int FmaxParticipants { get; set; }
        /// <summary>
        /// 活動描述
        /// </summary>
        public string FDescription { get; set; }
        /// <summary>
        /// 活動新增時間
        /// </summary>
        public DateTime FCreateTime { get; set; }

        public virtual ICollection<TActivityParticipants> TActivityParticipants { get; set; }
    }
}