// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TActivities
    {
        public TActivities()
        {
            TActivityParticipants = new HashSet<TActivityParticipants>();
        }

        public int FId { get; set; }
        public string FActivityId { get; set; }
        public string FActivityTitle { get; set; }
        public string FDateTime { get; set; }
        public int FmaxParticipants { get; set; }
        public string FDescription { get; set; }
        public string FCreateTime { get; set; }

        public virtual ICollection<TActivityParticipants> TActivityParticipants { get; set; }
    }
}