// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TAdministrators
    {
        public int FId { get; set; }
        public string FAdministratorId { get; set; }
        public string FLastName { get; set; }
        public string FFirstName { get; set; }
        public string FEmail { get; set; }
        public string FPasswordHash { get; set; }
        public string FPasswordSalt { get; set; }
        public string FSignUpTime { get; set; }
    }
}