// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TAreas
    {
        public TAreas()
        {
            TMembers = new HashSet<TMembers>();
        }

        public int FAreaId { get; set; }
        public string FName { get; set; }
        public int FCityId { get; set; }

        public virtual TCities FCity { get; set; }
        public virtual ICollection<TMembers> TMembers { get; set; }
    }
}