// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TCities
    {
        public int FCityId { get; set; }
        public string FCityName { get; set; }
    }
}