// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TDirectors
    {
        public TDirectors()
        {
            TMovieDirectorDetails = new HashSet<TMovieDirectorDetails>();
        }

        public int FDirectorId { get; set; }
        public string FDitectorName { get; set; }

        public virtual ICollection<TMovieDirectorDetails> TMovieDirectorDetails { get; set; }
    }
}