// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TFriends
    {
        public int FId { get; set; }
        public int FMemberId { get; set; }
        public int FFriendNo { get; set; }
        /// <summary>
        /// 好友的ID
        /// </summary>
        public int FFriendId { get; set; }
        /// <summary>
        /// 成為好友的時間
        /// </summary>
        public string FFriendDateTime { get; set; }

        public virtual TMembers FMember { get; set; }
    }
}