// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TMemberReports
    {
        /// <summary>
        /// 檢舉的流水號
        /// </summary>
        public int FMemberReportId { get; set; }
        /// <summary>
        /// 被檢舉的會員ID
        /// </summary>
        public int FReportedMemberId { get; set; }
        /// <summary>
        /// 檢舉者的會員ID
        /// </summary>
        public string FReportMemberId { get; set; }
        /// <summary>
        /// 檢舉類型
        /// </summary>
        public int FReportType { get; set; }
        /// <summary>
        /// 檢舉時間
        /// </summary>
        public DateTime FReportTime { get; set; }
    }
}