// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TMemberStatus
    {
        public int FStatusId { get; set; }
        public string FStatus { get; set; }
        public string FDescription { get; set; }
    }
}