// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TMemberPoints
    {
        public int FId { get; set; }
        public int FMemberId { get; set; }
        public int FItemNo { get; set; }
        public int? FPointsAdded { get; set; }
        public int? FPointDeducted { get; set; }
        public string FDescription { get; set; }
        public string FCreateTime { get; set; }

        public virtual TMembers FMember { get; set; }
    }
}