// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TMembers
    {
        public TMembers()
        {
            TActivityParticipants = new HashSet<TActivityParticipants>();
            TArticles = new HashSet<TArticles>();
            TComments = new HashSet<TComments>();
            TFriends = new HashSet<TFriends>();
            TMemberFavoriteMovieCategories = new HashSet<TMemberFavoriteMovieCategories>();
            TMemberPoints = new HashSet<TMemberPoints>();
            TOrders = new HashSet<TOrders>();
        }

        public int FId { get; set; }
        public string FMemberId { get; set; }
        /// <summary>
        /// 姓氏
        /// </summary>
        public string FLastName { get; set; }
        /// <summary>
        /// 名字
        /// </summary>
        public string FFirstName { get; set; }
        public string FEmail { get; set; }
        /// <summary>
        /// 密碼
        /// </summary>
        public string FPasswordHash { get; set; }
        public string FPasswordSalt { get; set; }
        public string FDateOfBirth { get; set; }
        public int? FGenderId { get; set; }
        /// <summary>
        /// 手機號碼
        /// </summary>
        public string FCellphone { get; set; }
        public string FAddress { get; set; }
        public int? FAreaId { get; set; }
        public string FPhotoPath { get; set; }
        /// <summary>
        /// 個人簡介
        /// </summary>
        public string FIntroduction { get; set; }
        public int? FTotalMemberPoint { get; set; }
        /// <summary>
        /// 註冊時間
        /// </summary>
        public string FSignUpTime { get; set; }

        public virtual TAreas FArea { get; set; }
        public virtual TGender FGender { get; set; }
        public virtual ICollection<TActivityParticipants> TActivityParticipants { get; set; }
        public virtual ICollection<TArticles> TArticles { get; set; }
        public virtual ICollection<TComments> TComments { get; set; }
        public virtual ICollection<TFriends> TFriends { get; set; }
        public virtual ICollection<TMemberFavoriteMovieCategories> TMemberFavoriteMovieCategories { get; set; }
        public virtual ICollection<TMemberPoints> TMemberPoints { get; set; }
        public virtual ICollection<TOrders> TOrders { get; set; }
    }
}