// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TMemberFavoriteMovieCategories
    {
        public int FId { get; set; }
        public int FMemberId { get; set; }
        public int FMovieCategoryId { get; set; }

        public virtual TMembers FMember { get; set; }
        public virtual TMovieCategories FMovieCategory { get; set; }
    }
}