// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TProductOrderDetails
    {
        public int FId { get; set; }
        public int FProductItemNo { get; set; }
        public int FOrderId { get; set; }
        public int FProductId { get; set; }
        public string FProductName { get; set; }
        public decimal FProductUnitprice { get; set; }
        public int FProductQty { get; set; }
        public decimal FProductDiscount { get; set; }
        public decimal FProductSubtotal { get; set; }

        public virtual TOrders FOrder { get; set; }
        public virtual TProducts FProduct { get; set; }
    }
}