// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TReports
    {
        public TReports()
        {
            TMemberReports = new HashSet<TMemberReports>();
        }

        /// <summary>
        /// 檢舉類型ID
        /// </summary>
        public int FReportTypeId { get; set; }
        /// <summary>
        /// 檢舉類型
        /// </summary>
        public string FReportType { get; set; }
        /// <summary>
        /// 檢舉類型的詳細描述
        /// </summary>
        public string FDescription { get; set; }

        public virtual ICollection<TMemberReports> TMemberReports { get; set; }
    }
}