// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TReport
    {
        public int FReportId { get; set; }
        public int FReportedMemberId { get; set; }
        public string FReportMemberId { get; set; }
        public string FReportDate { get; set; }
    }
}