// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TSeats
    {
        public TSeats()
        {
            TTicketOrderDetails = new HashSet<TTicketOrderDetails>();
        }

        public int FSeatId { get; set; }
        public string FSeatRow { get; set; }
        public int FSeatColumn { get; set; }

        public virtual ICollection<TTicketOrderDetails> TTicketOrderDetails { get; set; }
    }
}