// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TSessions
    {
        public TSessions()
        {
            TTicketOrderDetails = new HashSet<TTicketOrderDetails>();
        }

        public int FSessionId { get; set; }
        public int FMovieId { get; set; }
        public int FRoomId { get; set; }
        public int FCinemaId { get; set; }
        public DateTime FSessionDate { get; set; }
        public TimeSpan FSessionTime { get; set; }
        public decimal? FTicketPrice { get; set; }

        public virtual TCinemas FCinema { get; set; }
        public virtual TMovies FMovie { get; set; }
        public virtual TRooms FRoom { get; set; }
        public virtual ICollection<TTicketOrderDetails> TTicketOrderDetails { get; set; }
    }
}