// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpan.InseparableCore.Models
{
    public partial class TTicketOrderDetails
    {
        public int FId { get; set; }
        public int FTicketItemNo { get; set; }
        public int FOrderId { get; set; }
        public int FMovieId { get; set; }
        public string FMovieName { get; set; }
        public int FSessionId { get; set; }
        public int FSeatId { get; set; }
        public int FRoomId { get; set; }
        public decimal FTicketUnitprice { get; set; }
        public decimal FTicketDiscount { get; set; }
        public decimal FTicketSubtotal { get; set; }

        public virtual TMovies FMovie { get; set; }
        public virtual TOrders FOrder { get; set; }
        public virtual TRooms FRoom { get; set; }
        public virtual TSeats FSeat { get; set; }
        public virtual TSessions FSession { get; set; }
    }
}